######################################################################
# Automatically generated by qmake (2.01a) sab gen 28 12:59:14 2017
######################################################################

QT += widgets

TEMPLATE = app
TARGET = VirusLab_1.0
INCLUDEPATH += .

# Input
HEADERS += admin.h \
           admincontroller.h \
           controllerutente.h \
           dbutenti.h \
           dbvirus.h \
           mainwindow.h \
           smartutente.h \
           smartvirus.h \
           ui_mainwindow.h \
           usercontroller.h \
           utente.h \
           utentebasic.h \
           utentefree.h \
           utentepremium.h \
           virus.h
SOURCES += admin.cpp \
           admincontroller.cpp \
           controllerutente.cpp \
           dbutenti.cpp \
           dbvirus.cpp \
           main.cpp \
           mainwindow.cpp \
           smartutente.cpp \
           smartvirus.cpp \
           usercontroller.cpp \
           utente.cpp \
           utentebasic.cpp \
           utentefree.cpp \
           utentepremium.cpp \
           virus.cpp
